Angelina
new-okaerinasai/food pull request #10
Opened 2020-04-03 08:33 UTC by Angelina-Yaroshenko

added loss and train for it.

2020-04-03 09:21 UTC, svdcvt requested changes

2020-04-03 09:21 UTC, svdcvt commented on experiments/train_glass.py
> +class net_2last_layers(torch.nn.Module):
классы называть надо с большой буквы + как-то странно через нижнее подчеркивание

2020-04-03 09:21 UTC, svdcvt commented on experiments/train_glass.py
> +    def __init__(self,mod):
я не хочу щас везде править пробелы и прочее по PEP8, но я уже вижу много

2020-04-03 09:21 UTC, svdcvt commented on experiments/train_glass.py
> +    parser = argparse.ArgumentParser()
посмотри в ветке руслана мы отказались от аргпарса и делаем конфиги, наверное будет проще тебе сразу это поправить и уже это будет все норм в мастере

2020-04-03 09:21 UTC, svdcvt commented on experiments/train_glass.py
> +    criterion = glass_loss(alpha = 10.)
а альфа это гиперпараметр? если да то надо его в конфиг засунуть

2020-04-03 09:21 UTC, svdcvt commented on src/food/ood/loss.py
> +class glass_reg(torch.nn.Module):
тот же самый момент с названием, назови например GlassReg

2020-04-03 09:21 UTC, svdcvt commented on src/food/ood/loss.py
> +class glass_loss(torch.nn.Module):
GlassLoss

2020-04-03 09:21 UTC, svdcvt commented on src/food/ood/loss.py
> +class glass_simple_loss(torch.nn.Module):
GlassLossSimple

2020-04-03 09:21 UTC, svdcvt commented on src/food/ood/loss.py
> +
общий комментарий 
1) будет круто если будет поясняющая документация хотя бы кратко к новым штукам, что за класс, что делает
2) проверить техническую часть пока не могу, потому что не шарю
3) правь пеп

2020-04-04 12:24 UTC, svdcvt approved these changes

2020-04-04 17:02 UTC, new-okaerinasai approved these changes

2020-04-04 17:02 UTC, new-okaerinasai commented on src/food/ood/loss.py
> +class glass_reg(torch.nn.Module):
Назови файл не просто "loss", а более информативно -- у тебя же там не просто лосс, а именно GLaS.

2020-04-04 17:02 UTC, new-okaerinasai commented on src/food/ood/loss.py
> +        L=torch.norm(reg,p='fro')/n_classes**2
Поправь ВЕЗДЕ по pep8. Код не особо читаемый. Можно воспользоваться autopep8. Я внесу этот момент в CI.
```suggestion
        L = torch.norm(reg,p='fro' ) / n_classes ** 2
```

2020-04-04 17:02 UTC, new-okaerinasai commented on experiments/train_glass.py
> +import food
Общее замечание: к своему коду обязательно напиши тесты. Когда мы ревьювим, можем проглядеть какие-то моменты. Как их правильно писать, расскажу.

2020-04-04 17:02 UTC, merged